#!/bin/bash
# Script para comparar resultados da UI com Terminal

echo "=========================================="
echo "  Teste: UI vs Terminal - TF-IDF Search"
echo "=========================================="
echo ""

# Configurações
QUERY="machine learning algorithms"
DB="data/wiki-small.db"
TABLE="sample_articles"
ENTRIES=1000
THREADS=4

echo "Query: $QUERY"
echo "DB: $DB"
echo "Table: $TABLE"
echo "Entries: $ENTRIES"
echo "Threads: $THREADS"
echo ""
echo "=========================================="
echo "  Resultados do Terminal"
echo "=========================================="

# Executar busca no terminal
./app --db "$DB" --table "$TABLE" --entries "$ENTRIES" --nthreads "$THREADS" \
      --query_user "$QUERY" 2>&1 | grep -A 12 "Top 10"

echo ""
echo "=========================================="
echo "  Instruções para teste na UI"
echo "=========================================="
echo ""
echo "1. Compile e abra a UI:"
echo "   make ui"
echo ""
echo "2. Na interface:"
echo "   - Verifique que o banco é: data/wiki-small.db"
echo "   - Ajuste documentos para: 1000"
echo "     (use ALT + setas ou botões +/-)"
echo "   - Ajuste threads para: 4"
echo "     (use setas UP/DOWN ou botões +/-)"
echo ""
echo "3. Digite a query:"
echo "   $QUERY"
echo ""
echo "4. Clique em 'Buscar Documentos'"
echo ""
echo "5. Compare os resultados:"
echo "   - Número de resultados deve ser 10"
echo "   - Doc IDs devem ser idênticos"
echo "   - Scores devem ser iguais (4 casas decimais)"
echo "   - Textos devem corresponder"
echo ""
echo "=========================================="
echo "  Checklist de Verificação"
echo "=========================================="
echo ""
echo "[ ] UI mostra exatamente 10 resultados"
echo "[ ] Todos os 10 resultados são visíveis (não sobrepostos)"
echo "[ ] Doc IDs correspondem ao terminal"
echo "[ ] Scores correspondem ao terminal"
echo "[ ] Ordem dos resultados é idêntica"
echo "[ ] Textos dos documentos correspondem"
echo ""
echo "=========================================="
echo "  Controles da UI (Novo!)"
echo "=========================================="
echo ""
echo "Banco de Dados:"
echo "  CTRL + ← / →  : Trocar entre bancos"
echo ""
echo "Documentos:"
echo "  ALT + ← / →   : Ajustar quantidade (1k, 5k, 10k, 25k, 50k, Todos)"
echo "  Botões +/-    : Mesmo efeito"
echo ""
echo "Threads:"
echo "  ↑ / ↓         : Aumentar/diminuir (1-16)"
echo "  Botões +/-    : Mesmo efeito"
echo ""
echo "Navegação:"
echo "  Roda do mouse : Scroll vertical"
echo "  ESC           : Sair"
echo ""
